// Bluetooth FTMS UUIDs, equipment type enum, control point opcodes, and
// response/status code constants.

export const FTMS_SERVICE_UUID = "1826";
export const FTMS_SERVICE_UUID_LONG = "00001826-0000-1000-8000-00805f9b34fb";

export const FTMS_CHAR_UUIDS = {
  FITNESS_MACHINE_FEATURE: "2ACC",
  TREADMILL_DATA: "2ACD",
  CROSS_TRAINER_DATA: "2ACE",
  STEP_CLIMBER_DATA: "2ACF",
  STAIR_CLIMBER_DATA: "2AD0",
  ROWER_DATA: "2AD1",
  INDOOR_BIKE_DATA: "2AD2",
  TRAINING_STATUS: "2AD3",
  SUPPORTED_SPEED_RANGE: "2AD4",
  SUPPORTED_INCLINATION_RANGE: "2AD5",
  SUPPORTED_RESISTANCE_LEVEL_RANGE: "2AD6",
  SUPPORTED_HEART_RATE_RANGE: "2AD7",
  SUPPORTED_POWER_RANGE: "2AD8",
  FITNESS_MACHINE_CONTROL_POINT: "2AD9",
  FITNESS_MACHINE_STATUS: "2ADA",
} as const;

export const HEART_RATE_SERVICE_UUID = "180D";
export const HEART_RATE_MEASUREMENT_UUID = "2A37";

export enum EquipmentType {
  Treadmill = "treadmill",
  CrossTrainer = "cross_trainer",
  StepClimber = "step_climber",
  StairClimber = "stair_climber",
  Rower = "rower",
  IndoorBike = "indoor_bike",
  Unknown = "unknown",
}

export const CONTROL_POINT_OPCODES = {
  REQUEST_CONTROL: 0x00,
  RESET: 0x01,
  SET_SPEED_TARGET: 0x02,
  SET_INCLINATION_TARGET: 0x03,
  SET_RESISTANCE_TARGET: 0x04,
  SET_POWER_TARGET: 0x05,
  SET_HEART_RATE_TARGET: 0x06,
  START_RESUME: 0x07,
  STOP_PAUSE: 0x08,
  SET_INDOR_BIKE_SIMULATION: 0x11,
  SET_WHEEL_CIRCUMFERENCE: 0x12,
  SET_SPIN_DOWN_CONTROL: 0x13,
  SET_LATITUDE_AND_LONGITUDE: 0x14,
} as const;

export const CONTROL_POINT_RESPONSE_CODES = {
  RESERVED: 0x00,
  SUCCESS: 0x01,
  NOT_SUPPORTED: 0x02,
  INVALID_PARAMETER: 0x03,
  OPERATION_FAILED: 0x04,
  CONTROL_NOT_PERMITTED: 0x05,
} as const;

export const FITNESS_MACHINE_STATUS_OPCODES = {
  STOPPED_BY_USER: 0x01,
  STARTED_BY_USER: 0x02,
  STOPPED_BY_ERROR: 0x03,
  STOPPED_BY_USER_PROMPT: 0x04,
  STOPPED_BY_STANDBY: 0x05,
  STARTED_BY_USER_PROMPT: 0x06,
  STARTED_BY_SERVER: 0x07,
  CONTROL_PERMISSION_LOST: 0x08,
} as const;
